export const BUSCAR_POKEMON = 'BUSCAR_POKEMON';
export const OBTENER_POKEMONS = 'OBTENER_POKEMONS';
export const FILTRAR_POKEMON = 'FILTRAR_POKEMON';
export const POKEMON_ACTUAL = 'POKEMON_ACTUAL';
export const MOSTRAR_DATOS = 'MOSTRAR_DATOS';
export const MOSTRAR_STATS = 'MOSTRAR_STATS';
export const MOSTRAR_MOVES = 'MOSTRAR_MOVES';